name: Prettier

on: push

jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Prettier Action
        # You may pin to the exact commit or the version.
        # uses: creyD/prettier_action@6602189cf8bac1ce73ffe601925f6127ab7f21ac
        uses: creyD/prettier_action@v4.2
        # with:
          # Commit message, will be ignored if used with same_commit
          # commit_message: # optional, default is Prettified Code!
          # Extended commit message, will be ignored if used with same_commit
          # commit_description: # optional, default is 
          # Update the current commit instead of creating a new one
          # same_commit: # optional
          # Commit options
          # commit_options: # optional
          # Git push options
          # push_options: # optional
          # File pattern used for `git add`, can't be used with only_changed!
          # file_pattern: # optional, default is *
          # Options for the `prettier` command
          # prettier_options: # optional, default is --write **/*.js
          # Running the script in dry mode just shows whether there are files that should be prettified or not
          # dry: # optional
          # Specific version of prettier (by default just use the latest version)
          # prettier_version: # optional
          # Specify a directory to cd into before installing prettier and running it
          # working_directory: # optional
          # Only prettify files changed in the last commit, can't be used with file_pattern!
          # only_changed: # optional
          # Install Prettier plugins, i.e. `@prettier/plugin-php @prettier/plugin-other`
          # prettier_plugins: # optional, default is 
          # GitHub Token or PAT token used to authenticate against a repository
          # github_token: # optional, default is ${{ github.token }}
