name: CI/CD Main

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x

      - name: Install packages
        run: npm install

      - name: Optimize assets
        run: npx expo-optimize

        # fix --release-channel not available for web yet
      - name: Select environment
        run: cp -f app/env/Environment.Prod.ts app/env/Environment.ts

      - name: Build for web
        run: expo build:web
